name: bump-version

on:
  push:
    branches:
      - master

jobs:
  bump-and-push-tag:
    runs-on: ubuntu-latest
    container: ghcr.io/kazanexpress/commitizen:v2
    if: "!contains(github.event.head_commit.message, 'bump:')"

    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: lint commit message
        run: |
          git config --global --add safe.directory /__w/keycloak-kazanexpress/keycloak-kazanexpress
          cz check -m "$(git log -1 --pretty=%B)"
      - name: bump & push
        run: |
          git config --global user.name 'Machine User'
          git config --global user.email 'ghmachine@kazanexpress.ru'
          git remote set-url origin https://x-access-token:${{ secrets.GH_MACHINE_RW_TOKEN }}@github.com/${{ github.repository }}
          cz bump --changelog
          git push origin HEAD:master && git push --tags